EncuestaProject/EncuestaProject/Models/ENCUESTA.cs
namespace EncuestaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("ENCUESTA")]
    public partial class ENCUESTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENCUESTA()
        {
            CAMPO = new HashSet<CAMPO>();
            DET_ENC = new HashSet<DET_ENC>();
        }

        public int id { get; set; }

        [Required]
        [StringLength(50)]
        public string nombre { get; set; }

        [StringLength(200)]
        public string descripcion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO> CAMPO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DET_ENC> DET_ENC { get; set; }
    }
}

EncuestaProject/EncuestaProject/Controllers/EncuestaController.cs
using EncuestaProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EncuestaProject.Controllers
{
    
    [Authorize]
    public class EncuestaController : Controller
    {
        // GET: Encuesta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Crear()
        {
            return View();
        }

        public ActionResult Consultar()
        {
            return View();
        }
    }
}

EncuestaProject/EncuestaProject/Views/Encuesta/Consultar.cshtml
@{
    ViewBag.Title = "Consultar";
}

<h2>Consultar</h2>

EncuestaProject/EncuestaProject/Views/Encuesta/Crear.cshtml
@model EncuestaProject.Models.ENCUESTA
@{
    ViewBag.Title = "Crear";
}

<h2>Creacion de Encuesta</h2>
@using (Html.BeginForm())
{
    @Html.LabelFor(c => c.nombre, "Nombre")
    @Html.TextBoxFor(c => c.nombre, new { type = "text" })
    <br />
    @Html.LabelFor(c => c.descripcion, "descripcion")
    @Html.TextAreaFor(c => c.descripcion, new { type = "text" })
    <br />
}

EncuestaProject/EncuestaProject/Views/Encuesta/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Bienvenido a las Encuestas, que desea realizar?</h2>

<ul>
    <li>@Html.ActionLink("Crear Encuesta", "Crear", "Encuesta")</li>
    <li>@Html.ActionLink("Mostrar Encuestas", "Consultar", "Encuesta")</li>
</ul>